server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_user
    username: project_user
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret: hellojwttoken
    validity: 86400000